language: php
php:
  - '7.1'

before_script:
  - curl -s http://getcomposer.org/installer | php
  - composer install -n

script:
   - php bin/console doctrine:database:create --env=test
   - php bin/console doctrine:schema:create --env=test
   - vendor/bin/phpunit --coverage-clover build/coverage/xml

after_script:
   - vendor/bin/codacycoverage clover build/coverage/xml
